apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: king-istio
  name: king-istio
  namespace: kingfisher-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: king-istio
  template:
    metadata:
      labels:
        app: king-istio
    spec:
      containers:
      - image: openkingfisher/king-istio:latest
        name: king-istio
        ports:
        - containerPort: 8080
          name: http
        livenessProbe: 
          tcpSocket: 
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe: 
          tcpSocket: 
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 512m
            memory: 512Mi
        env:
        - name: DB_URL
          value: 'root:kingfisher@tcp(king-mysql:3306)/kingfisher'
        - name: LISTEN
          value: '0.0.0.0'
        - name: PORT
          value: '8080'
        - name: RABBITMQ_URL
          value: "amqp://kingfisher:kingfisher@king-rabbitmq:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: king-istio
  namespace: kingfisher-system
spec:
  ports:
  - name: king-istio
    port: 8080
    targetPort: 8080
  selector:
    app: king-istio
  sessionAffinity: ClientIP
